SMA Crossover:
  short_window: 50
  long_window: 200
  entry_condition: "short_sma > long_sma"
  exit_condition: "short_sma < long_sma"

RSI Oversold:
  window_length: 14
  entry_condition: "rsi < 30"
  exit_condition: "rsi > 70"